# Predicting a known dataframe
This testset data frame has been carefully removed from the original dataset. We will perform three predictions based on three algorithms namely, Logistic Regression, Binary Classifier and Random Forest Classifier depending upon the training dataset.
The labeled data is already known, we will tally how accurate our result is upon this dataset.

In [106]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle
import math
import re

In [85]:
dtf1=pd.read_csv("Rent_In_Advance_Testset.csv")
dtf1

Unnamed: 0  Applied Gender Payment_Method Location Received  \
0           96163  $524.00      F             RP        O  $524.00   
1           91210  $250.00      M             RP       PP  $250.00   
2           65529  $136.00      F             AV       NE  $136.00   
3          113243  $300.00      F             AV       NE  $300.00   
4           87702  $560.00      F             AV        M  $560.00   
...           ...      ...    ...            ...      ...      ...   
28532        2138  $300.00      F             AV        M  $300.00   
28533      131172  $940.00      F             AV        M  $940.00   
28534       81761  $330.00      F             AV        O  $330.00   
28535       26170  $720.00      M             AV       NE  $720.00   
28536       76958  $420.00      M             AV        M  $420.00   

                 Id Reason       Date    Age Area  True_False  
0      GHI001206283     RA  09-Jul-18  30-34    O           0  
1      GHI000753413     RA  26-Jun-19  50-54   AM           0  
2      GHI000112669     RA  07-Sep-20  50-54    O           0  
3      GHI000094993     RA  28-Mar-20  30-34   EC           0  
4      GHI001536010     RA  17-May-18  30-34   AM           0  
...             ...    ...        ...    ...  ...         ...  
28532  GHI001306368     RA  20-Sep-17  20-24   AM           0  
28533  GHI000807686     RA  26-Sep-17  30-34   AM           0  
28534  GHI001418001     RA  29-Sep-17  35-39    W           0  
28535  GHI000091148     RA  27-Jan-20  50-54    C           0  
28536  GHI000079941     RA  04-Sep-19  45-49    W           0  

[28537 rows x 12 columns]

In [90]:
dtf2=pd.read_csv("concatfd.csv")
dtf2

Applied Gender Payment Method Location  Received           Id Reason  \
0       339      M             AV       AM    339.25  XXXXXXXXXXX     CR   
1       950      F             AV        C    950.00  XXXXXXXXXXX     CR   
2      1139     GD             RP       BP   1138.50  XXXXXXXXXXX     CR   
3      1650      M             RP        O   1650.00  XXXXXXXXXXX     RA   
4       341      F              U        W    341.00  XXXXXXXXXXX     RA   
5      2915     GD              U       EC   2915.25  XXXXXXXXXXX     RA   
6      2599      F             AV        T   2599.00  XXXXXXXXXXX     RA   
7      1783      F             AV        N   1782.50  XXXXXXXXXXX     RA   
8      1955      F             AV        S   1955.00  XXXXXXXXXXX     TB   
9      1955      F             RP       NL   1955.00  XXXXXXXXXXX     TB   
10     2561      F             AV      Wlg   2561.00  XXXXXXXXXXX     TB   
11     2875      F             AV       AM   2875.00  XXXXXXXXXXX     TB   

                   Date    Age Area  
0   2017-02-09 00:00:00  25-29    O  
1   2017-02-17 00:00:00  35-39    M  
2   2017-09-29 00:00:00  45-49    M  
3   2018-05-07 00:00:00  30-34   PP  
4   2018-11-19 00:00:00  20-24    M  
5   2019-02-01 00:00:00     16   NE  
6   2019-03-13 00:00:00     17    O  
7   2019-04-10 00:00:00    65+   PP  
8   2019-04-11 00:00:00  18-19    U  
9   2019-04-15 00:00:00  55-59   PP  
10  2019-07-09 00:00:00  40-44    M  
11  2019-09-06 00:00:00  50-54    U

In [91]:
frame=[dtf1,dtf2]
dtf=pd.concat(frame)

In [92]:
dtf=dtf.drop("Unnamed: 0",axis=1)

In [93]:
dtf['Applied']=dtf['Applied'].replace(r'',np.NaN)
dtf.dropna()
dtf['Applied']=dtf['Applied'].replace('[A-Z a-z , / ? \ : " ; $]','' ,regex=True)
dtf['Applied']=dtf['Applied'].astype(float)

dtf['Received']=dtf['Received'].replace(r'',np.NaN)
dtf.dropna()
dtf['Received']=dtf['Received'].replace('[A-Z a-z , / ? \ : " ; $]','' ,regex=True)
dtf['Received']=dtf['Received'].astype(float)

In [94]:
'''
dtf['Date'] = pd.to_datetime(dtf['Date'], errors='coerce')
dtf['Year'] = pd.DatetimeIndex(dtf['Date']).year
dtf['Month'] = pd.DatetimeIndex(dtf['Date']).month
dtf['Day']= pd.DatetimeIndex(dtf['Date']).day
dtf['Week Of Month']= dtf['Date'].apply(lambda d: (d.day-1)//7+1)
dtf['Week Of Year']= pd.DatetimeIndex(dtf['Date']).weekofyear
'''

"\ndtf['Date'] = pd.to_datetime(dtf['Date'], errors='coerce')\ndtf['Year'] = pd.DatetimeIndex(dtf['Date']).year\ndtf['Month'] = pd.DatetimeIndex(dtf['Date']).month\ndtf['Day']= pd.DatetimeIndex(dtf['Date']).day\ndtf['Week Of Month']= dtf['Date'].apply(lambda d: (d.day-1)//7+1)\ndtf['Week Of Year']= pd.DatetimeIndex(dtf['Date']).weekofyear\n"

In [95]:
dtf

Applied Gender Payment_Method Location  Received            Id Reason  \
0     524.0      F             RP        O     524.0  GHI001206283     RA   
1     250.0      M             RP       PP     250.0  GHI000753413     RA   
2     136.0      F             AV       NE     136.0  GHI000112669     RA   
3     300.0      F             AV       NE     300.0  GHI000094993     RA   
4     560.0      F             AV        M     560.0  GHI001536010     RA   
..      ...    ...            ...      ...       ...           ...    ...   
7    1783.0      F            NaN        N    1782.5   XXXXXXXXXXX     RA   
8    1955.0      F            NaN        S    1955.0   XXXXXXXXXXX     TB   
9    1955.0      F            NaN       NL    1955.0   XXXXXXXXXXX     TB   
10   2561.0      F            NaN      Wlg    2561.0   XXXXXXXXXXX     TB   
11   2875.0      F            NaN       AM    2875.0   XXXXXXXXXXX     TB   

                   Date    Age Area  True_False Payment Method  
0             09-Jul-18  30-34    O         0.0            NaN  
1             26-Jun-19  50-54   AM         0.0            NaN  
2             07-Sep-20  50-54    O         0.0            NaN  
3             28-Mar-20  30-34   EC         0.0            NaN  
4             17-May-18  30-34   AM         0.0            NaN  
..                  ...    ...  ...         ...            ...  
7   2019-04-10 00:00:00    65+   PP         NaN             AV  
8   2019-04-11 00:00:00  18-19    U         NaN             AV  
9   2019-04-15 00:00:00  55-59   PP         NaN             RP  
10  2019-07-09 00:00:00  40-44    M         NaN             AV  
11  2019-09-06 00:00:00  50-54    U         NaN             AV  

[28549 rows x 12 columns]

In [96]:
mapper = {"16" : "Teenage", "17" : "Teenage", "18-19" : "Adult", "20-24": "Adult",
          "25-29" : "Adult", "30-34" : "MidAge", "35-39" : "MidAge", "40-44" : "MidAge",
          "45-49" : "MidAge", "50-54" : "Old", "55-59" : "Old", "60-64" : "Old", "65+":"Old"}

In [97]:
dtf["AgeGroup"] = dtf["Age"].map(mapper)

In [98]:
pmapper = {"AV":"AV","RP":"RPU", "U":"RPU"}

In [99]:
dtf["Payment_Type"] = dtf["Payment_Method"].map(pmapper)

In [100]:
dtf["logapplied"] = pd.Series(np.log(dtf["Applied"]), index = dtf.index)
dtf["logreceived"] = pd.Series(np.log(dtf["Received"]), index = dtf.index)

In [107]:
def add_datepart(df, fldname, drop=True):
    fld = df[fldname]
    if not np.issubdtype(fld.dtype, np.datetime64):
        df[fldname] = fld = pd.to_datetime(fld, infer_datetime_format=True)
    targ_pre = re.sub('[Dd]ate$', '', fldname)
    for n in ('Year', 'Month', 'Week', 'Day', 'Dayofweek', 'Dayofyear',
            'Is_month_end', 'Is_month_start', 'Is_quarter_end', 'Is_quarter_start', 'Is_year_end', 'Is_year_start'):
        df[targ_pre+n] = getattr(fld.dt,n.lower())
    df[targ_pre+'Elapsed'] = fld.astype(np.int64) // 10**9
    if drop: df.drop(fldname, axis=1, inplace=True)

In [108]:
add_datepart(dtf, "Date")

<ipython-input-107-aa99c3778298>:8: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.
  df[targ_pre+n] = getattr(fld.dt,n.lower())


In [109]:
dtf.columns

Index(['Applied', 'Gender', 'Payment_Method', 'Location', 'Received', 'Id',
       'Reason', 'Age', 'Area', 'True_False', 'Payment Method', 'AgeGroup',
       'Payment_Type', 'logapplied', 'logreceived', 'Year', 'Month', 'Week',
       'Day', 'Dayofweek', 'Dayofyear', 'Is_month_end', 'Is_month_start',
       'Is_quarter_end', 'Is_quarter_start', 'Is_year_end', 'Is_year_start',
       'Elapsed'],
      dtype='object')

In [121]:
dataf=dtf.copy()

In [122]:
#del dataf['Date']
del dataf['Gender']
del dataf['Id']
del dataf['Applied']
del dataf['Received']
del dataf['Age']
del dataf['Reason']
del dataf['Payment_Method']
## Removed highly correlated KPIS
#del dataf["Week_Of_Month"]
#del dataf["Week_Of_Year"]
del dataf['logreceived']
#del dataf['Ratio']
del dataf['Dayofweek']
#del dataf['Dayofyear']
del dataf['Is_month_end']
del dataf['Is_month_start']
del dataf['Is_quarter_end']
del dataf['Is_quarter_start']
del dataf['Is_year_end']
del dataf['Is_year_start']

In [123]:
dataf=pd.get_dummies(dataf,drop_first=True)

dataf

True_False  logapplied  Year  Month  Week  Day  Dayofyear     Elapsed  \
0          0.0    6.261492  2018      7    28    9        190  1531094400   
1          0.0    5.521461  2019      6    26   26        177  1561507200   
2          0.0    4.912655  2020      9    37    7        251  1599436800   
3          0.0    5.703782  2020      3    13   28         88  1585353600   
4          0.0    6.327937  2018      5    20   17        137  1526515200   
..         ...         ...   ...    ...   ...  ...        ...         ...   
7          NaN    7.486053  2019      4    15   10        100  1554854400   
8          NaN    7.578145  2019      4    15   11        101  1554940800   
9          NaN    7.578145  2019      4    16   15        105  1555286400   
10         NaN    7.848153  2019      7    28    9        190  1562630400   
11         NaN    7.963808  2019      9    36    6        249  1567728000   

    Location_BP  Location_C  ...  Area_T  Area_U  Area_W  Area_Wlg  \
0             0           0  ...       0       0       0         0   
1             0           0  ...       0       0       0         0   
2             0           0  ...       0       0       0         0   
3             0           0  ...       0       0       0         0   
4             0           0  ...       0       0       0         0   
..          ...         ...  ...     ...     ...     ...       ...   
7             0           0  ...       0       0       0         0   
8             0           0  ...       0       1       0         0   
9             0           0  ...       0       0       0         0   
10            0           0  ...       0       0       0         0   
11            0           0  ...       0       1       0         0   

    Payment Method_RP  Payment Method_U  AgeGroup_MidAge  AgeGroup_Old  \
0                   0                 0                1             0   
1                   0                 0                0             1   
2                   0                 0                0             1   
3                   0                 0                1             0   
4                   0                 0                1             0   
..                ...               ...              ...           ...   
7                   0                 0                0             1   
8                   0                 0                0             0   
9                   1                 0                0             1   
10                  0                 0                1             0   
11                  0                 0                0             1   

    AgeGroup_Teenage  Payment_Type_RPU  
0                  0                 1  
1                  0                 1  
2                  0                 0  
3                  0                 0  
4                  0                 0  
..               ...               ...  
7                  0                 0  
8                  0                 0  
9                  0                 0  
10                 0                 0  
11                 0                 0  

[28549 rows x 42 columns]

In [124]:
dataf.columns

Index(['True_False', 'logapplied', 'Year', 'Month', 'Week', 'Day', 'Dayofyear',
       'Elapsed', 'Location_BP', 'Location_C', 'Location_EC', 'Location_M',
       'Location_N', 'Location_NE', 'Location_NL', 'Location_O', 'Location_PP',
       'Location_S', 'Location_T', 'Location_U', 'Location_W', 'Location_Wlg',
       'Area_BP', 'Area_C', 'Area_EC', 'Area_M', 'Area_N', 'Area_NE',
       'Area_NL', 'Area_O', 'Area_PP', 'Area_S', 'Area_T', 'Area_U', 'Area_W',
       'Area_Wlg', 'Payment Method_RP', 'Payment Method_U', 'AgeGroup_MidAge',
       'AgeGroup_Old', 'AgeGroup_Teenage', 'Payment_Type_RPU'],
      dtype='object')

In [125]:
Xx=dataf[['logapplied', 'Year', 'Month', 'Week', 'Day', 'Dayofyear',
       'Elapsed', 'Location_NE', 'Location_O', 'Location_PP', 'Location_U',
       'Area_BP', 'Area_C', 'Area_EC', 'Area_N', 'Area_NL', 'Area_O', 'Area_S',
       'Area_T', 'Area_W', 'Area_Wlg', 'AgeGroup_MidAge', 'AgeGroup_Old',
       'AgeGroup_Teenage', 'Payment_Type_RPU']]

In [126]:
loaded_model = pickle.load(open('LR_trained_model.sav', 'rb'))
#result = loaded_model.score(Xx, yy)
#print(result)
sc = pickle.load(open('scaler1.sav','rb'))

In [127]:
Xx = sc.transform(Xx)

In [128]:
Ypred = loaded_model.predict(Xx)

In [129]:
y_pred_probability=loaded_model.predict(Xx)
y_pred_probability

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [134]:
dfl=dtf.drop(dtf[dtf["Id"]=='XXXXXXXXXXX'].index)

In [135]:
dfl

Applied Gender Payment_Method Location  Received            Id Reason  \
12       140.0      M             AV       NE     140.0  GHI000317709     RA   
13       550.0      F             AV       PP     550.0  GHI000722944     RA   
14       570.0      M             AV        M     570.0  GHI000074516     RA   
15       280.0      M             AV       NE     280.0  GHI000086558     RA   
16       360.0      F             AV        M     360.0  GHI001380874     RA   
...        ...    ...            ...      ...       ...           ...    ...   
28532    300.0      F             AV        M     300.0  GHI001306368     RA   
28533    940.0      F             AV        M     940.0  GHI000807686     RA   
28534    330.0      F             AV        O     330.0  GHI001418001     RA   
28535    720.0      M             AV       NE     720.0  GHI000091148     RA   
28536    420.0      M             AV        M     420.0  GHI000079941     RA   

         Age Area  True_False  ... Day Dayofweek Dayofyear  Is_month_end  \
12     55-59    S         0.0  ...   7         0       251         False   
13     25-29   AM         0.0  ...   1         4        32         False   
14     25-29   AM         0.0  ...  23         3       327         False   
15     50-54    C         0.0  ...   5         2       186         False   
16     20-24    W         0.0  ...  27         3       208         False   
...      ...  ...         ...  ...  ..       ...       ...           ...   
28532  20-24   AM         0.0  ...  20         2       263         False   
28533  30-34   AM         0.0  ...  26         1       269         False   
28534  35-39    W         0.0  ...  29         4       272         False   
28535  50-54    C         0.0  ...  27         0        27         False   
28536  45-49    W         0.0  ...   4         2       247         False   

       Is_month_start  Is_quarter_end  Is_quarter_start  Is_year_end  \
12              False           False             False        False   
13               True           False             False        False   
14              False           False             False        False   
15              False           False             False        False   
16              False           False             False        False   
...               ...             ...               ...          ...   
28532           False           False             False        False   
28533           False           False             False        False   
28534           False           False             False        False   
28535           False           False             False        False   
28536           False           False             False        False   

       Is_year_start     Elapsed  
12             False  1599436800  
13             False  1548979200  
14             False  1511395200  
15             False  1499212800  
16             False  1501113600  
...              ...         ...  
28532          False  1505865600  
28533          False  1506384000  
28534          False  1506643200  
28535          False  1580083200  
28536          False  1567555200  

[28525 rows x 28 columns]

In [141]:
dtf3=pd.read_csv("Rent_In_Advance_Testset.csv")

In [142]:
y=dtf3['True_False']

In [143]:
p=Ypred[0:-12]
p

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [144]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y,p)
print(cm)
accuracy_score(y,p)*100

[[17857 10571]
 [    2   107]]


62.94985457476259

# Binary Classifier

In [145]:
loaded_model = pickle.load(open('Binary_Classifier_Training_Data.sav', 'rb'))
#result = loaded_model.score(Xx, yy)
#print(result)
Ypred2 = loaded_model.predict(Xx)

In [146]:
Ypred2

array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

In [147]:
p=Ypred2[0:-12]

In [148]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y,p)
print(cm)
accuracy_score(y,p)*100

[[22263  6165]
 [   14    95]]


78.347408627396

# Random Forest

In [160]:
loaded_model = pickle.load(open('Random_Forest_Classifier_Training_Data.sav', 'rb'))
#result = loaded_model.score(Xx, yy)
#print(result)
Ypred3 = loaded_model.predict(Xx)

In [161]:
Ypred3

array([1, 1, 0, ..., 1, 1, 1], dtype=int64)

In [162]:
p=Ypred3[0:-12]

In [163]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y,p)
print(cm)
accuracy_score(y,p)*100

[[21597  6831]
 [   11    98]]


76.02410905140694

# Voting Classifier

In [165]:
loaded_model = pickle.load(open('Voting_Classifier_Training_Data.sav', 'rb'))
#result = loaded_model.score(Xx, yy)
#print(result)
Ypred4 = loaded_model.predict(Xx)

In [166]:
Ypred4

array([1, 0, 0, ..., 1, 1, 1], dtype=int64)

In [167]:
p=Ypred4[0:-12]

In [168]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y,p)
print(cm)
accuracy_score(y,p)*100

[[21820  6608]
 [   11    98]]


76.80555068857974

# Saving prediction in an excel file

In [169]:
prediction1 = pd.DataFrame(Ypred, columns=['predictionsLR'])
prediction2 = pd.DataFrame(Ypred2, columns=['predictionsBC'])
prediction3 = pd.DataFrame(Ypred3, columns=['predictionsRFC'])
prediction4 = pd.DataFrame(Ypred4, columns=['predictionsVC'])

frames=[dtf3,prediction1,prediction2,prediction3,prediction4]

result = pd.concat(frames,axis=1)

In [171]:
result.to_excel("Prediction_Known_Testset.xlsx")