# Predicting a known dataframe
This testset data frame has been carefully removed from the original dataset. We will perform three predictions based on three algorithms namely, Logistic Regression, Binary Classifier and Random Forest Classifier depending upon the training dataset.
The labeled data is already known, we will tally how accurate our result is upon this dataset.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle
import math
import re

In [2]:
dtf1=pd.read_csv("Tenancy_Bond_Testset.csv")
dtf1

Unnamed: 0    Applied Gender Payment_Method Location   Received  \
0          120628  $1,760.00      F             AV       NE  $1,760.00   
1           73316  $1,360.00      M             RP        M  $1,360.00   
2          108895  $1,200.00      M             RP       NE  $1,200.00   
3           41066  $3,100.00      F             AV        M  $3,100.00   
4           62592    $460.00      F             AV        M    $460.00   
...           ...        ...    ...            ...      ...        ...   
29347      145390    $660.00      M             AV        M    $660.00   
29348       96069  $1,360.00      F             AV        M  $1,360.00   
29349       99535    $700.00      F             RP       NE    $700.00   
29350       49365    $208.00      F             AV        M    $208.00   
29351       30923  $1,290.00      F             AV       NE  $1,290.00   

                 Id Reason       Date    Age Area  True_False  
0      GHI000081283     TB  19-Sep-19  35-39   BP           0  
1      GHI000402974     TB  05-Jun-19  35-39   BP           0  
2      GHI000085542     TB  28-Nov-18  20-24    C           0  
3      GHI001497095     TB  18-Sep-18  30-34   BP           0  
4      GHI000358933     TB  05-Nov-18  45-49   AM           0  
...             ...    ...        ...    ...  ...         ...  
29347  GHI001255684     TB  12-Dec-17  35-39   AM           0  
29348  GHI000134418     TB  20-Feb-18  35-39   EC           0  
29349  GHI001743643     TB  20-Jun-19  40-44    C           0  
29350  GHI000112669     TB  06-Jan-17  25-29    O           0  
29351  GHI000941326     TB  15-May-19  45-49   AM           0  

[29352 rows x 12 columns]

In [4]:
dtf2=pd.read_csv("concatfd.csv")
dtf2

Applied Gender Payment Method Location  Received           Id Reason  \
0       339      M             AV       AM    339.25  XXXXXXXXXXX     CR   
1       950      F             AV        C    950.00  XXXXXXXXXXX     CR   
2      1139     GD             RP       BP   1138.50  XXXXXXXXXXX     CR   
3      1650      M             RP        O   1650.00  XXXXXXXXXXX     RA   
4       341      F              U        W    341.00  XXXXXXXXXXX     RA   
5      2915     GD              U       EC   2915.25  XXXXXXXXXXX     RA   
6      2599      F             AV        T   2599.00  XXXXXXXXXXX     RA   
7      1783      F             AV        N   1782.50  XXXXXXXXXXX     RA   
8      1955      F             AV        S   1955.00  XXXXXXXXXXX     TB   
9      1955      F             RP       NL   1955.00  XXXXXXXXXXX     TB   
10     2561      F             AV      Wlg   2561.00  XXXXXXXXXXX     TB   
11     2875      F             AV       AM   2875.00  XXXXXXXXXXX     TB   

                   Date    Age Area  
0   2017-02-09 00:00:00  25-29    O  
1   2017-02-17 00:00:00  35-39    M  
2   2017-09-29 00:00:00  45-49    M  
3   2018-05-07 00:00:00  30-34   PP  
4   2018-11-19 00:00:00  20-24    M  
5   2019-02-01 00:00:00     16   NE  
6   2019-03-13 00:00:00     17    O  
7   2019-04-10 00:00:00    65+   PP  
8   2019-04-11 00:00:00  18-19    U  
9   2019-04-15 00:00:00  55-59   PP  
10  2019-07-09 00:00:00  40-44    M  
11  2019-09-06 00:00:00  50-54    U

In [5]:
frame=[dtf1,dtf2]
dtf=pd.concat(frame)

In [6]:
dtf=dtf.drop("Unnamed: 0",axis=1)

In [7]:
dtf['Applied']=dtf['Applied'].replace(r'',np.NaN)
dtf.dropna()
dtf['Applied']=dtf['Applied'].replace('[A-Z a-z , / ? \ : " ; $]','' ,regex=True)
dtf['Applied']=dtf['Applied'].astype(float)

dtf['Received']=dtf['Received'].replace(r'',np.NaN)
dtf.dropna()
dtf['Received']=dtf['Received'].replace('[A-Z a-z , / ? \ : " ; $]','' ,regex=True)
dtf['Received']=dtf['Received'].astype(float)

In [8]:
'''
dtf['Date'] = pd.to_datetime(dtf['Date'], errors='coerce')
dtf['Year'] = pd.DatetimeIndex(dtf['Date']).year
dtf['Month'] = pd.DatetimeIndex(dtf['Date']).month
dtf['Day']= pd.DatetimeIndex(dtf['Date']).day
dtf['Week Of Month']= dtf['Date'].apply(lambda d: (d.day-1)//7+1)
dtf['Week Of Year']= pd.DatetimeIndex(dtf['Date']).weekofyear
'''

"\ndtf['Date'] = pd.to_datetime(dtf['Date'], errors='coerce')\ndtf['Year'] = pd.DatetimeIndex(dtf['Date']).year\ndtf['Month'] = pd.DatetimeIndex(dtf['Date']).month\ndtf['Day']= pd.DatetimeIndex(dtf['Date']).day\ndtf['Week Of Month']= dtf['Date'].apply(lambda d: (d.day-1)//7+1)\ndtf['Week Of Year']= pd.DatetimeIndex(dtf['Date']).weekofyear\n"

In [9]:
dtf

Applied Gender Payment_Method Location  Received            Id Reason  \
0    1760.0      F             AV       NE    1760.0  GHI000081283     TB   
1    1360.0      M             RP        M    1360.0  GHI000402974     TB   
2    1200.0      M             RP       NE    1200.0  GHI000085542     TB   
3    3100.0      F             AV        M    3100.0  GHI001497095     TB   
4     460.0      F             AV        M     460.0  GHI000358933     TB   
..      ...    ...            ...      ...       ...           ...    ...   
7    1783.0      F            NaN        N    1782.5   XXXXXXXXXXX     RA   
8    1955.0      F            NaN        S    1955.0   XXXXXXXXXXX     TB   
9    1955.0      F            NaN       NL    1955.0   XXXXXXXXXXX     TB   
10   2561.0      F            NaN      Wlg    2561.0   XXXXXXXXXXX     TB   
11   2875.0      F            NaN       AM    2875.0   XXXXXXXXXXX     TB   

                   Date    Age Area  True_False Payment Method  
0             19-Sep-19  35-39   BP         0.0            NaN  
1             05-Jun-19  35-39   BP         0.0            NaN  
2             28-Nov-18  20-24    C         0.0            NaN  
3             18-Sep-18  30-34   BP         0.0            NaN  
4             05-Nov-18  45-49   AM         0.0            NaN  
..                  ...    ...  ...         ...            ...  
7   2019-04-10 00:00:00    65+   PP         NaN             AV  
8   2019-04-11 00:00:00  18-19    U         NaN             AV  
9   2019-04-15 00:00:00  55-59   PP         NaN             RP  
10  2019-07-09 00:00:00  40-44    M         NaN             AV  
11  2019-09-06 00:00:00  50-54    U         NaN             AV  

[29364 rows x 12 columns]

In [10]:
mapper = {"16" : "Teenage", "17" : "Teenage", "18-19" : "Adult", "20-24": "Adult",
          "25-29" : "Adult", "30-34" : "MidAge", "35-39" : "MidAge", "40-44" : "MidAge",
          "45-49" : "MidAge", "50-54" : "Old", "55-59" : "Old", "60-64" : "Old", "65+":"Old"}

In [11]:
dtf["AgeGroup"] = dtf["Age"].map(mapper)

In [12]:
pmapper = {"AV":"AV","RP":"RPU", "U":"RPU"}

In [13]:
dtf["Payment_Type"] = dtf["Payment_Method"].map(pmapper)

In [14]:
dtf["logapplied"] = pd.Series(np.log(dtf["Applied"]), index = dtf.index)
dtf["logreceived"] = pd.Series(np.log(dtf["Received"]), index = dtf.index)

In [15]:
def add_datepart(df, fldname, drop=True):
    fld = df[fldname]
    if not np.issubdtype(fld.dtype, np.datetime64):
        df[fldname] = fld = pd.to_datetime(fld, infer_datetime_format=True)
    targ_pre = re.sub('[Dd]ate$', '', fldname)
    for n in ('Year', 'Month', 'Week', 'Day', 'Dayofweek', 'Dayofyear',
            'Is_month_end', 'Is_month_start', 'Is_quarter_end', 'Is_quarter_start', 'Is_year_end', 'Is_year_start'):
        df[targ_pre+n] = getattr(fld.dt,n.lower())
    df[targ_pre+'Elapsed'] = fld.astype(np.int64) // 10**9
    if drop: df.drop(fldname, axis=1, inplace=True)

In [16]:
add_datepart(dtf, "Date")

<ipython-input-15-aa99c3778298>:8: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.
  df[targ_pre+n] = getattr(fld.dt,n.lower())


In [17]:
dtf.columns

Index(['Applied', 'Gender', 'Payment_Method', 'Location', 'Received', 'Id',
       'Reason', 'Age', 'Area', 'True_False', 'Payment Method', 'AgeGroup',
       'Payment_Type', 'logapplied', 'logreceived', 'Year', 'Month', 'Week',
       'Day', 'Dayofweek', 'Dayofyear', 'Is_month_end', 'Is_month_start',
       'Is_quarter_end', 'Is_quarter_start', 'Is_year_end', 'Is_year_start',
       'Elapsed'],
      dtype='object')

In [18]:
dataf=dtf.copy()

In [19]:
#del dataf['Date']
del dataf['Gender']
del dataf['Id']
del dataf['Applied']
del dataf['Received']
del dataf['Age']
del dataf['Reason']
del dataf['Payment_Method']
## Removed highly correlated KPIS
#del dataf["Week_Of_Month"]
#del dataf["Week_Of_Year"]
del dataf['logreceived']
#del dataf['Ratio']
del dataf['Dayofweek']
#del dataf['Dayofyear']
del dataf['Is_month_end']
del dataf['Is_month_start']
del dataf['Is_quarter_end']
del dataf['Is_quarter_start']
del dataf['Is_year_end']
del dataf['Is_year_start']

In [20]:
dataf=pd.get_dummies(dataf,drop_first=True)

dataf

True_False  logapplied  Year  Month  Week  Day  Dayofyear     Elapsed  \
0          0.0    7.473069  2019      9    38   19        262  1568851200   
1          0.0    7.215240  2019      6    23    5        156  1559692800   
2          0.0    7.090077  2018     11    48   28        332  1543363200   
3          0.0    8.039157  2018      9    38   18        261  1537228800   
4          0.0    6.131226  2018     11    45    5        309  1541376000   
..         ...         ...   ...    ...   ...  ...        ...         ...   
7          NaN    7.486053  2019      4    15   10        100  1554854400   
8          NaN    7.578145  2019      4    15   11        101  1554940800   
9          NaN    7.578145  2019      4    16   15        105  1555286400   
10         NaN    7.848153  2019      7    28    9        190  1562630400   
11         NaN    7.963808  2019      9    36    6        249  1567728000   

    Location_BP  Location_C  ...  Area_T  Area_U  Area_W  Area_Wlg  \
0             0           0  ...       0       0       0         0   
1             0           0  ...       0       0       0         0   
2             0           0  ...       0       0       0         0   
3             0           0  ...       0       0       0         0   
4             0           0  ...       0       0       0         0   
..          ...         ...  ...     ...     ...     ...       ...   
7             0           0  ...       0       0       0         0   
8             0           0  ...       0       1       0         0   
9             0           0  ...       0       0       0         0   
10            0           0  ...       0       0       0         0   
11            0           0  ...       0       1       0         0   

    Payment Method_RP  Payment Method_U  AgeGroup_MidAge  AgeGroup_Old  \
0                   0                 0                1             0   
1                   0                 0                1             0   
2                   0                 0                0             0   
3                   0                 0                1             0   
4                   0                 0                1             0   
..                ...               ...              ...           ...   
7                   0                 0                0             1   
8                   0                 0                0             0   
9                   1                 0                0             1   
10                  0                 0                1             0   
11                  0                 0                0             1   

    AgeGroup_Teenage  Payment_Type_RPU  
0                  0                 0  
1                  0                 1  
2                  0                 1  
3                  0                 0  
4                  0                 0  
..               ...               ...  
7                  0                 0  
8                  0                 0  
9                  0                 0  
10                 0                 0  
11                 0                 0  

[29364 rows x 42 columns]

In [21]:
dataf.columns

Index(['True_False', 'logapplied', 'Year', 'Month', 'Week', 'Day', 'Dayofyear',
       'Elapsed', 'Location_BP', 'Location_C', 'Location_EC', 'Location_M',
       'Location_N', 'Location_NE', 'Location_NL', 'Location_O', 'Location_PP',
       'Location_S', 'Location_T', 'Location_U', 'Location_W', 'Location_Wlg',
       'Area_BP', 'Area_C', 'Area_EC', 'Area_M', 'Area_N', 'Area_NE',
       'Area_NL', 'Area_O', 'Area_PP', 'Area_S', 'Area_T', 'Area_U', 'Area_W',
       'Area_Wlg', 'Payment Method_RP', 'Payment Method_U', 'AgeGroup_MidAge',
       'AgeGroup_Old', 'AgeGroup_Teenage', 'Payment_Type_RPU'],
      dtype='object')

In [22]:
Xx=dataf[['logapplied', 'Year', 'Month', 'Week', 'Day', 'Dayofyear',
       'Elapsed', 'Location_NE', 'Location_O', 'Location_PP', 'Location_U',
       'Area_BP', 'Area_C', 'Area_EC', 'Area_N', 'Area_NL', 'Area_O', 'Area_S',
       'Area_T', 'Area_W', 'Area_Wlg', 'AgeGroup_MidAge', 'AgeGroup_Old',
       'AgeGroup_Teenage', 'Payment_Type_RPU']]

In [23]:
loaded_model = pickle.load(open('LR_trained_model.sav', 'rb'))
#result = loaded_model.score(Xx, yy)
#print(result)
sc = pickle.load(open('scaler1.sav','rb'))

In [24]:
Xx = sc.transform(Xx)

In [25]:
Ypred = loaded_model.predict(Xx)

In [26]:
y_pred_probability=loaded_model.predict(Xx)
y_pred_probability

array([1, 0, 0, ..., 1, 1, 1], dtype=int64)

In [27]:
dfl=dtf.drop(dtf[dtf["Id"]=='XXXXXXXXXXX'].index)

In [28]:
dfl

Applied Gender Payment_Method Location  Received            Id Reason  \
12      1968.0      M             AV       NE    1968.0  GHI000097292     TB   
13      2000.0      M             AV        M    2000.0  GHI001071876     TB   
14       210.0      M             AV        M     210.0  GHI000375313     TB   
15       300.0      F             AV        M     300.0  GHI002062082     TB   
16       560.0      F             AV       NE     560.0  GHI000161437     TB   
...        ...    ...            ...      ...       ...           ...    ...   
29347    660.0      M             AV        M     660.0  GHI001255684     TB   
29348   1360.0      F             AV        M    1360.0  GHI000134418     TB   
29349    700.0      F             RP       NE     700.0  GHI001743643     TB   
29350    208.0      F             AV        M     208.0  GHI000112669     TB   
29351   1290.0      F             AV       NE    1290.0  GHI000941326     TB   

         Age Area  True_False  ... Day Dayofweek Dayofyear  Is_month_end  \
12     35-39    C         0.0  ...   3         4        62         False   
13     40-44    C         0.0  ...  30         3        30         False   
14     60-64    T         0.0  ...   2         3       184         False   
15     25-29    O         0.0  ...  10         3       254         False   
16     25-29    S         0.0  ...  18         4       138         False   
...      ...  ...         ...  ...  ..       ...       ...           ...   
29347  35-39   AM         0.0  ...  12         1       346         False   
29348  35-39   EC         0.0  ...  20         1        51         False   
29349  40-44    C         0.0  ...  20         3       171         False   
29350  25-29    O         0.0  ...   6         4         6         False   
29351  45-49   AM         0.0  ...  15         2       135         False   

       Is_month_start  Is_quarter_end  Is_quarter_start  Is_year_end  \
12              False           False             False        False   
13              False           False             False        False   
14              False           False             False        False   
15              False           False             False        False   
16              False           False             False        False   
...               ...             ...               ...          ...   
29347           False           False             False        False   
29348           False           False             False        False   
29349           False           False             False        False   
29350           False           False             False        False   
29351           False           False             False        False   

       Is_year_start     Elapsed  
12             False  1488499200  
13             False  1580342400  
14             False  1593648000  
15             False  1599696000  
16             False  1526601600  
...              ...         ...  
29347          False  1513036800  
29348          False  1519084800  
29349          False  1560988800  
29350          False  1483660800  
29351          False  1557878400  

[29340 rows x 28 columns]

In [30]:
dtf3=pd.read_csv("Tenancy_Bond_Testset.csv")

In [31]:
y=dtf3['True_False']

In [32]:
p=Ypred[0:-12]
p

array([1, 0, 0, ..., 0, 0, 1], dtype=int64)

In [33]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y,p)
print(cm)
accuracy_score(y,p)*100

[[15004 14265]
 [    1    82]]


51.39683837557918

# Binary Classifier

In [34]:
loaded_model = pickle.load(open('Binary_Classifier_Training_Data.sav', 'rb'))
#result = loaded_model.score(Xx, yy)
#print(result)
Ypred2 = loaded_model.predict(Xx)

In [35]:
Ypred2

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [36]:
p=Ypred2[0:-12]

In [37]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y,p)
print(cm)
accuracy_score(y,p)*100

[[22164  7105]
 [    8    75]]


75.76655764513491

# Random Forest

In [38]:
loaded_model = pickle.load(open('Random_Forest_Classifier_Training_Data.sav', 'rb'))
#result = loaded_model.score(Xx, yy)
#print(result)
Ypred3 = loaded_model.predict(Xx)

In [39]:
Ypred3

array([0, 1, 0, ..., 1, 1, 1], dtype=int64)

In [40]:
p=Ypred3[0:-12]

In [41]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y,p)
print(cm)
accuracy_score(y,p)*100

[[21848  7421]
 [    8    75]]


74.68997001907877

# Voting Classifier

In [42]:
loaded_model = pickle.load(open('Voting_Classifier_Training_Data.sav', 'rb'))
#result = loaded_model.score(Xx, yy)
#print(result)
Ypred4 = loaded_model.predict(Xx)

In [43]:
Ypred4

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [44]:
p=Ypred4[0:-12]

In [45]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y,p)
print(cm)
accuracy_score(y,p)*100

[[21901  7368]
 [    6    77]]


74.87735077677841

# Saving prediction in an excel file

In [46]:
prediction1 = pd.DataFrame(Ypred, columns=['predictionsLR'])
prediction2 = pd.DataFrame(Ypred2, columns=['predictionsBC'])
prediction3 = pd.DataFrame(Ypred3, columns=['predictionsRFC'])
prediction4 = pd.DataFrame(Ypred4, columns=['predictionsVC'])

frames=[dtf3,prediction1,prediction2,prediction3,prediction4]

result = pd.concat(frames,axis=1)

In [47]:
result.to_excel("Prediction_Known_Testset.xlsx")