# Predicting a known dataframe
This testset data frame has been carefully removed from the original dataset. We will perform three predictions based on three algorithms namely, Logistic Regression, Binary Classifier and Random Forest Classifier depending upon the training dataset.
The labeled data is already known, we will tally how accurate our result is upon this dataset.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle
import math
import re

In [2]:
dtf1=pd.read_csv("Car_Rent_Testset.csv")
dtf1

Unnamed: 0    Applied Gender Payment_Method Location   Received  \
0          22830    $625.00      F             AV       PP    $625.00   
1          32835    $460.00      F             AV        M    $460.00   
2            163    $360.00      M             AV        M    $360.00   
3           2844    $780.00      M             AV       NE    $780.00   
4          21742    $200.00      M             AV        M    $200.00   
...          ...        ...    ...            ...      ...        ...   
7765       19719  $1,000.00      F             AV       NE  $1,000.00   
7766        9897    $400.00      F             AV        M    $400.00   
7767       11340    $697.00      F             AV        M    $696.75   
7768        5892    $300.00      F             AV        M    $300.00   
7769       36771    $625.00      F             AV        M    $625.00   

                Id Reason       Date    Age Area  True_False  
0     GHI001712135     CR  30-Apr-19  40-44   AM           0  
1     GHI000140573     CR  12-Nov-18  25-29   AM           0  
2     GHI001357314     CR  13-Dec-18  50-54    O           0  
3     GHI001588756     CR  20-Aug-18  60-64    T           0  
4     GHI000075311     CR  08-Aug-18  25-29   NL           0  
...            ...    ...        ...    ...  ...         ...  
7765  GHI001763083     CR  23-Jul-19  25-29    C           0  
7766  GHI001260818     CR  04-Dec-17  60-64   AM           0  
7767  GHI001486088     CR  06-Nov-18  45-49    T           0  
7768  GHI000380221     CR  30-Jun-17  25-29   NL           0  
7769  GHI000185631     CR  28-Jan-20  35-39   AM           0  

[7770 rows x 12 columns]

In [3]:
dtf2=pd.read_csv("concatfd.csv")
dtf2

Applied Gender Payment Method Location  Received           Id Reason  \
0       339      M             AV       AM    339.25  XXXXXXXXXXX     CR   
1       950      F             AV        C    950.00  XXXXXXXXXXX     CR   
2      1139     GD             RP       BP   1138.50  XXXXXXXXXXX     CR   
3      1650      M             RP        O   1650.00  XXXXXXXXXXX     RA   
4       341      F              U        W    341.00  XXXXXXXXXXX     RA   
5      2915     GD              U       EC   2915.25  XXXXXXXXXXX     RA   
6      2599      F             AV        T   2599.00  XXXXXXXXXXX     RA   
7      1783      F             AV        N   1782.50  XXXXXXXXXXX     RA   
8      1955      F             AV        S   1955.00  XXXXXXXXXXX     TB   
9      1955      F             RP       NL   1955.00  XXXXXXXXXXX     TB   
10     2561      F             AV      Wlg   2561.00  XXXXXXXXXXX     TB   
11     2875      F             AV       AM   2875.00  XXXXXXXXXXX     TB   

                   Date    Age Area  
0   2017-02-09 00:00:00  25-29    O  
1   2017-02-17 00:00:00  35-39    M  
2   2017-09-29 00:00:00  45-49    M  
3   2018-05-07 00:00:00  30-34   PP  
4   2018-11-19 00:00:00  20-24    M  
5   2019-02-01 00:00:00     16   NE  
6   2019-03-13 00:00:00     17    O  
7   2019-04-10 00:00:00    65+   PP  
8   2019-04-11 00:00:00  18-19    U  
9   2019-04-15 00:00:00  55-59   PP  
10  2019-07-09 00:00:00  40-44    M  
11  2019-09-06 00:00:00  50-54    U

In [4]:
frame=[dtf1,dtf2]
dtf=pd.concat(frame)

In [5]:
dtf=dtf.drop("Unnamed: 0",axis=1)

In [6]:
dtf['Applied']=dtf['Applied'].replace(r'',np.NaN)
dtf.dropna()
dtf['Applied']=dtf['Applied'].replace('[A-Z a-z , / ? \ : " ; $]','' ,regex=True)
dtf['Applied']=dtf['Applied'].astype(float)

dtf['Received']=dtf['Received'].replace(r'',np.NaN)
dtf.dropna()
dtf['Received']=dtf['Received'].replace('[A-Z a-z , / ? \ : " ; $]','' ,regex=True)
dtf['Received']=dtf['Received'].astype(float)

In [7]:
'''
dtf['Date'] = pd.to_datetime(dtf['Date'], errors='coerce')
dtf['Year'] = pd.DatetimeIndex(dtf['Date']).year
dtf['Month'] = pd.DatetimeIndex(dtf['Date']).month
dtf['Day']= pd.DatetimeIndex(dtf['Date']).day
dtf['Week Of Month']= dtf['Date'].apply(lambda d: (d.day-1)//7+1)
dtf['Week Of Year']= pd.DatetimeIndex(dtf['Date']).weekofyear
'''

"\ndtf['Date'] = pd.to_datetime(dtf['Date'], errors='coerce')\ndtf['Year'] = pd.DatetimeIndex(dtf['Date']).year\ndtf['Month'] = pd.DatetimeIndex(dtf['Date']).month\ndtf['Day']= pd.DatetimeIndex(dtf['Date']).day\ndtf['Week Of Month']= dtf['Date'].apply(lambda d: (d.day-1)//7+1)\ndtf['Week Of Year']= pd.DatetimeIndex(dtf['Date']).weekofyear\n"

In [8]:
dtf

Applied Gender Payment_Method Location  Received            Id Reason  \
0     625.0      F             AV       PP     625.0  GHI001712135     CR   
1     460.0      F             AV        M     460.0  GHI000140573     CR   
2     360.0      M             AV        M     360.0  GHI001357314     CR   
3     780.0      M             AV       NE     780.0  GHI001588756     CR   
4     200.0      M             AV        M     200.0  GHI000075311     CR   
..      ...    ...            ...      ...       ...           ...    ...   
7    1783.0      F            NaN        N    1782.5   XXXXXXXXXXX     RA   
8    1955.0      F            NaN        S    1955.0   XXXXXXXXXXX     TB   
9    1955.0      F            NaN       NL    1955.0   XXXXXXXXXXX     TB   
10   2561.0      F            NaN      Wlg    2561.0   XXXXXXXXXXX     TB   
11   2875.0      F            NaN       AM    2875.0   XXXXXXXXXXX     TB   

                   Date    Age Area  True_False Payment Method  
0             30-Apr-19  40-44   AM         0.0            NaN  
1             12-Nov-18  25-29   AM         0.0            NaN  
2             13-Dec-18  50-54    O         0.0            NaN  
3             20-Aug-18  60-64    T         0.0            NaN  
4             08-Aug-18  25-29   NL         0.0            NaN  
..                  ...    ...  ...         ...            ...  
7   2019-04-10 00:00:00    65+   PP         NaN             AV  
8   2019-04-11 00:00:00  18-19    U         NaN             AV  
9   2019-04-15 00:00:00  55-59   PP         NaN             RP  
10  2019-07-09 00:00:00  40-44    M         NaN             AV  
11  2019-09-06 00:00:00  50-54    U         NaN             AV  

[7782 rows x 12 columns]

In [9]:
mapper = {"16" : "Teenage", "17" : "Teenage", "18-19" : "Adult", "20-24": "Adult",
          "25-29" : "Adult", "30-34" : "MidAge", "35-39" : "MidAge", "40-44" : "MidAge",
          "45-49" : "MidAge", "50-54" : "Old", "55-59" : "Old", "60-64" : "Old", "65+":"Old"}

In [10]:
dtf["AgeGroup"] = dtf["Age"].map(mapper)

In [11]:
pmapper = {"AV":"AV","RP":"RPU", "U":"RPU"}

In [12]:
dtf["Payment_Type"] = dtf["Payment_Method"].map(pmapper)

In [13]:
dtf["logapplied"] = pd.Series(np.log(dtf["Applied"]), index = dtf.index)
dtf["logreceived"] = pd.Series(np.log(dtf["Received"]), index = dtf.index)

In [14]:
def add_datepart(df, fldname, drop=True):
    fld = df[fldname]
    if not np.issubdtype(fld.dtype, np.datetime64):
        df[fldname] = fld = pd.to_datetime(fld, infer_datetime_format=True)
    targ_pre = re.sub('[Dd]ate$', '', fldname)
    for n in ('Year', 'Month', 'Week', 'Day', 'Dayofweek', 'Dayofyear',
            'Is_month_end', 'Is_month_start', 'Is_quarter_end', 'Is_quarter_start', 'Is_year_end', 'Is_year_start'):
        df[targ_pre+n] = getattr(fld.dt,n.lower())
    df[targ_pre+'Elapsed'] = fld.astype(np.int64) // 10**9
    if drop: df.drop(fldname, axis=1, inplace=True)

In [15]:
add_datepart(dtf, "Date")

<ipython-input-14-aa99c3778298>:8: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.
  df[targ_pre+n] = getattr(fld.dt,n.lower())


In [16]:
dtf.columns

Index(['Applied', 'Gender', 'Payment_Method', 'Location', 'Received', 'Id',
       'Reason', 'Age', 'Area', 'True_False', 'Payment Method', 'AgeGroup',
       'Payment_Type', 'logapplied', 'logreceived', 'Year', 'Month', 'Week',
       'Day', 'Dayofweek', 'Dayofyear', 'Is_month_end', 'Is_month_start',
       'Is_quarter_end', 'Is_quarter_start', 'Is_year_end', 'Is_year_start',
       'Elapsed'],
      dtype='object')

In [17]:
dataf=dtf.copy()

In [18]:
#del dataf['Date']
del dataf['Gender']
del dataf['Id']
del dataf['Applied']
del dataf['Received']
del dataf['Age']
del dataf['Reason']
del dataf['Payment_Method']
## Removed highly correlated KPIS
#del dataf["Week_Of_Month"]
#del dataf["Week_Of_Year"]
del dataf['logreceived']
#del dataf['Ratio']
del dataf['Dayofweek']
#del dataf['Dayofyear']
del dataf['Is_month_end']
del dataf['Is_month_start']
del dataf['Is_quarter_end']
del dataf['Is_quarter_start']
del dataf['Is_year_end']
del dataf['Is_year_start']

In [19]:
dataf=pd.get_dummies(dataf,drop_first=True)

dataf

True_False  logapplied  Year  Month  Week  Day  Dayofyear     Elapsed  \
0          0.0    6.437752  2019      4    18   30        120  1556582400   
1          0.0    6.131226  2018     11    46   12        316  1541980800   
2          0.0    5.886104  2018     12    50   13        347  1544659200   
3          0.0    6.659294  2018      8    34   20        232  1534723200   
4          0.0    5.298317  2018      8    32    8        220  1533686400   
..         ...         ...   ...    ...   ...  ...        ...         ...   
7          NaN    7.486053  2019      4    15   10        100  1554854400   
8          NaN    7.578145  2019      4    15   11        101  1554940800   
9          NaN    7.578145  2019      4    16   15        105  1555286400   
10         NaN    7.848153  2019      7    28    9        190  1562630400   
11         NaN    7.963808  2019      9    36    6        249  1567728000   

    Location_BP  Location_C  ...  Area_T  Area_U  Area_W  Area_Wlg  \
0             0           0  ...       0       0       0         0   
1             0           0  ...       0       0       0         0   
2             0           0  ...       0       0       0         0   
3             0           0  ...       1       0       0         0   
4             0           0  ...       0       0       0         0   
..          ...         ...  ...     ...     ...     ...       ...   
7             0           0  ...       0       0       0         0   
8             0           0  ...       0       1       0         0   
9             0           0  ...       0       0       0         0   
10            0           0  ...       0       0       0         0   
11            0           0  ...       0       1       0         0   

    Payment Method_RP  Payment Method_U  AgeGroup_MidAge  AgeGroup_Old  \
0                   0                 0                1             0   
1                   0                 0                0             0   
2                   0                 0                0             1   
3                   0                 0                0             1   
4                   0                 0                0             0   
..                ...               ...              ...           ...   
7                   0                 0                0             1   
8                   0                 0                0             0   
9                   1                 0                0             1   
10                  0                 0                1             0   
11                  0                 0                0             1   

    AgeGroup_Teenage  Payment_Type_RPU  
0                  0                 0  
1                  0                 0  
2                  0                 0  
3                  0                 0  
4                  0                 0  
..               ...               ...  
7                  0                 0  
8                  0                 0  
9                  0                 0  
10                 0                 0  
11                 0                 0  

[7782 rows x 42 columns]

In [20]:
dataf.columns

Index(['True_False', 'logapplied', 'Year', 'Month', 'Week', 'Day', 'Dayofyear',
       'Elapsed', 'Location_BP', 'Location_C', 'Location_EC', 'Location_M',
       'Location_N', 'Location_NE', 'Location_NL', 'Location_O', 'Location_PP',
       'Location_S', 'Location_T', 'Location_U', 'Location_W', 'Location_Wlg',
       'Area_BP', 'Area_C', 'Area_EC', 'Area_M', 'Area_N', 'Area_NE',
       'Area_NL', 'Area_O', 'Area_PP', 'Area_S', 'Area_T', 'Area_U', 'Area_W',
       'Area_Wlg', 'Payment Method_RP', 'Payment Method_U', 'AgeGroup_MidAge',
       'AgeGroup_Old', 'AgeGroup_Teenage', 'Payment_Type_RPU'],
      dtype='object')

In [21]:
Xx=dataf[['logapplied', 'Year', 'Month', 'Week', 'Day', 'Dayofyear',
       'Elapsed', 'Location_NE', 'Location_O', 'Location_PP', 'Location_U',
       'Area_BP', 'Area_C', 'Area_EC', 'Area_N', 'Area_NL', 'Area_O', 'Area_S',
       'Area_T', 'Area_W', 'Area_Wlg', 'AgeGroup_MidAge', 'AgeGroup_Old',
       'AgeGroup_Teenage', 'Payment_Type_RPU']]

In [22]:
loaded_model = pickle.load(open('LR_trained_model.sav', 'rb'))
#result = loaded_model.score(Xx, yy)
#print(result)
sc = pickle.load(open('scaler1.sav','rb'))

In [23]:
Xx = sc.transform(Xx)

In [24]:
Ypred = loaded_model.predict(Xx)

In [25]:
y_pred_probability=loaded_model.predict(Xx)
y_pred_probability

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [26]:
dfl=dtf.drop(dtf[dtf["Id"]=='XXXXXXXXXXX'].index)

In [27]:
dfl

Applied Gender Payment_Method Location  Received            Id Reason  \
12      220.0      M             AV        M    220.00  GHI000157228     CR   
13      960.0      F             AV       NE    960.00  GHI000144654     CR   
14      285.0      F             AV        M    285.00  GHI000761091     CR   
15      325.0      M             RP       PP    325.00  GHI000089345     CR   
16      600.0      F             AV        M    600.00  GHI000601882     CR   
...       ...    ...            ...      ...       ...           ...    ...   
7765   1000.0      F             AV       NE   1000.00  GHI001763083     CR   
7766    400.0      F             AV        M    400.00  GHI001260818     CR   
7767    697.0      F             AV        M    696.75  GHI001486088     CR   
7768    300.0      F             AV        M    300.00  GHI000380221     CR   
7769    625.0      F             AV        M    625.00  GHI000185631     CR   

        Age Area  True_False  ... Day Dayofweek Dayofyear  Is_month_end  \
12    40-44    S         0.0  ...   9         2       253         False   
13    20-24    N         0.0  ...  26         0       330         False   
14    30-34   BP         0.0  ...   3         0        34         False   
15    25-29    C         0.0  ...  23         0        23         False   
16    25-29   AM         0.0  ...   5         0       217         False   
...     ...  ...         ...  ...  ..       ...       ...           ...   
7765  25-29    C         0.0  ...  23         1       204         False   
7766  60-64   AM         0.0  ...   4         0       338         False   
7767  45-49    T         0.0  ...   6         1       310         False   
7768  25-29   NL         0.0  ...  30         4       181          True   
7769  35-39   AM         0.0  ...  28         1        28         False   

      Is_month_start  Is_quarter_end  Is_quarter_start  Is_year_end  \
12             False           False             False        False   
13             False           False             False        False   
14             False           False             False        False   
15             False           False             False        False   
16             False           False             False        False   
...              ...             ...               ...          ...   
7765           False           False             False        False   
7766           False           False             False        False   
7767           False           False             False        False   
7768           False            True             False        False   
7769           False           False             False        False   

      Is_year_start     Elapsed  
12            False  1599609600  
13            False  1543190400  
14            False  1580688000  
15            False  1485129600  
16            False  1564963200  
...             ...         ...  
7765          False  1563840000  
7766          False  1512345600  
7767          False  1541462400  
7768          False  1498780800  
7769          False  1580169600  

[7758 rows x 28 columns]

In [28]:
dtf3=pd.read_csv("Car_Rent_Testset.csv")

In [29]:
y=dtf3['True_False']

In [30]:
p=Ypred[0:-12]
p

array([1, 1, 1, ..., 0, 0, 1], dtype=int64)

In [31]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y,p)
print(cm)
accuracy_score(y,p)*100

[[2750 4931]
 [   0   89]]


36.53796653796654

# Binary Classifier

In [32]:
loaded_model = pickle.load(open('Binary_Classifier_Training_Data.sav', 'rb'))
#result = loaded_model.score(Xx, yy)
#print(result)
Ypred2 = loaded_model.predict(Xx)

In [33]:
Ypred2

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [34]:
p=Ypred2[0:-12]

In [35]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y,p)
print(cm)
accuracy_score(y,p)*100

[[5255 2426]
 [  14   75]]


68.5971685971686

# Random Forest

In [36]:
loaded_model = pickle.load(open('Random_Forest_Classifier_Training_Data.sav', 'rb'))
#result = loaded_model.score(Xx, yy)
#print(result)
Ypred3 = loaded_model.predict(Xx)

In [37]:
Ypred3

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [38]:
p=Ypred3[0:-12]

In [39]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y,p)
print(cm)
accuracy_score(y,p)*100

[[5090 2591]
 [  12   77]]


66.4993564993565

# Voting Classifier

In [40]:
loaded_model = pickle.load(open('Voting_Classifier_Training_Data.sav', 'rb'))
#result = loaded_model.score(Xx, yy)
#print(result)
Ypred4 = loaded_model.predict(Xx)

In [41]:
Ypred4

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [42]:
p=Ypred4[0:-12]

In [43]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y,p)
print(cm)
accuracy_score(y,p)*100

[[5084 2597]
 [  12   77]]


66.42213642213642

# Saving prediction in an excel file

In [44]:
prediction1 = pd.DataFrame(Ypred, columns=['predictionsLR'])
prediction2 = pd.DataFrame(Ypred2, columns=['predictionsBC'])
prediction3 = pd.DataFrame(Ypred3, columns=['predictionsRFC'])
prediction4 = pd.DataFrame(Ypred4, columns=['predictionsVC'])

frames=[dtf3,prediction1,prediction2,prediction3,prediction4]

result = pd.concat(frames,axis=1)

In [45]:
result.to_excel("Prediction_Known_Testset.xlsx")